package org.jboss.ddoyle.drools.cep.sample;

import org.jboss.ddoyle.drools.demo.model.v1.SimpleEvent;

declare SimpleEvent
    @role( event )
    @timestamp( timestamp.getTime() )
    @expires( 2d )
end

rule "SimpleTestRule-Two"
when
	$s:SimpleEvent()
	not SimpleEvent(this != $s, this after [0,10s] $s)
then
	System.out.println("Rule Two: There's no event matching the following event within 10 seconds: " + $s);
end

