package org.jboss.ddoyle.drools.cep.sample;

import org.jboss.ddoyle.drools.demo.model.v1.SimpleEvent;

declare SimpleEvent
    @role( event )
    @timestamp( timestamp )
    @expires( 2d )
end

global java.lang.String myNewGlobal

rule "SimpleTestRule-One"
when
	$s:SimpleEvent(code=="MY_CODE")
then
	System.out.println("Rule One: Found simple event: " + $s);
end

rule "SimpleTestRule-Two"
when
	$s:SimpleEvent(code=="MY_CODE")
	not SimpleEvent(this != $s, this after [0,10s] $s)
then
	System.out.println("Rule Two: There's no event matching the following event within 10 seconds: " + $s);
end

